# Generated by Django 5.0.7 on 2024-08-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
