# Generated by Django 5.0.7 on 2024-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
