# Generated by Django 5.0.7 on 2024-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_message_receiver_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_reciver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
