# Generated by Django 5.0.7 on 2024-09-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
