# Generated by Django 5.0.7 on 2025-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_message_replied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
