# Generated by Django 5.1.5 on 2025-02-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_message_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
