# Generated by Django 5.1.5 on 2025-02-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_user_google_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status_view',
            field=models.CharField(choices=[('seen', 'Seen'), ('delivered', 'Delivered'), ('sent', 'Sent')], default='sent', max_length=10),
        ),
    ]
