# Generated by Django 5.1.5 on 2025-02-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_message_status_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
