# Generated by Django 5.1.5 on 2025-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status_view',
            field=models.CharField(choices=[('seen', 'Seen'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='sent', max_length=10),
        ),
    ]
