# Generated by Django 5.1.5 on 2025-04-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_is_read_message_is_read_toggle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read_toggle',
        ),
        migrations.AlterField(
            model_name='message',
            name='status_view',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('seen', 'Seen'), ('sent', 'Sent')], default='sent', max_length=10),
        ),
    ]
