# Generated by Django 5.1.5 on 2025-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_message_is_read_toggle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_view',
            field=models.CharField(choices=[('seen', 'Seen'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='sent', max_length=10),
        ),
    ]
