# Generated by Django 5.1.5 on 2025-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_message_status_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_view',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=10),
        ),
    ]
