# Generated by Django 5.1.5 on 2025-04-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_message_status_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_view',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('seen', 'Seen'), ('sent', 'Sent')], default='sent', max_length=10),
        ),
    ]
